version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  method-exec-time-tracker:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: method-exec-time-tracker
    ports:
      - "8081:8080"

volumes:
  pgdata:
